M48
; DRILL file {KiCad 9.0.2} date 2025-07-09T14:42:09+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-09T14:42:09+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X152.21Y-115.21
X157.99Y-115.21
T2
X177.13Y-117.6
X185.13Y-117.6
M30
